name: hma
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7.*
  - pip
  - numpy
  - pandas
  - fastdtw=0.2.*
  - matplotlib=3.1.*
  - scikit-learn=0.21.*
  - scipy=1.2.*
  - seaborn=0.9.*
  - tslearn=0.1.*