def log_angles(ls, rs, lh, rh, el, er, kl, kr, frame: int):
    print(f"Joint angles for frame {[frame]}")
    print(f"---------------")
    print(f"Shoulder left\n--FlexEx: {ls['flexion_extension'][frame]}\n--AbdAdd: {ls['abduction_adduction'][frame]}")
    print(f"Shoulder right\n--FlexEx: {rs['flexion_extension'][frame]}\n--AbdAdd: {rs['abduction_adduction'][frame]}")
    print(f"Hip left\n--FlexEx: {lh['flexion_extension'][frame]}\n--AbdAdd: {lh['abduction_adduction'][frame]}")
    print(f"Hip right\n--FlexEx: {rh['flexion_extension'][frame]}\n--AbdAdd: {rh['abduction_adduction'][frame]}")
    print(f"Elbow left\n--FlexEx: {el['flexion_extension'][frame]}")
    print(f"Elbow right\n--FlexEx: {er['flexion_extension'][frame]}")
    print(f"Knee left\n--FlexEx: {kl['flexion_extension'][frame]}")
    print(f"Knee right\n--FlexEx: {kr['flexion_extension'][frame]}")